services:
  postgres:
    image: postgres:17.6
    environment:
    - POSTGRES_DB=projet_transversal
    - POSTGRES_USER=projet_transversal_user
    - POSTGRES_PASSWORD=projet_transversal
    ports:
    - 5432:5432
